export const stopIds = [
  {
    stopId: 30161,
    dir: "E",
    stopName: "18th (Loop-bound)",
    parentStopId: 40830,
  },
  {
    stopId: 30162,
    dir: "W",
    stopName: "18th (54th/Cermak-bound)",
    parentStopId: 40830,
  },
  {
    stopId: 30022,
    dir: "N",
    stopName: "35th/Archer (Loop-bound)",
    parentStopId: 40120,
  },
  {
    stopId: 30023,
    dir: "S",
    stopName: "35th/Archer (Midway-bound)",
    parentStopId: 40120,
  },
  {
    stopId: 30213,
    dir: "N",
    stopName: "35-Bronzeville-IIT (Harlem-bound)",
    parentStopId: 41120,
  },
  {
    stopId: 30214,
    dir: "S",
    stopName: "35-Bronzeville-IIT (63rd-bound)",
    parentStopId: 41120,
  },
  {
    stopId: 30245,
    dir: "N",
    stopName: "43rd (Harlem-bound)",
    parentStopId: 41270,
  },
  {
    stopId: 30246,
    dir: "S",
    stopName: "43rd (63rd-bound)",
    parentStopId: 41270,
  },
  {
    stopId: 30210,
    dir: "S",
    stopName: "47th (63rd-bound)",
    parentStopId: 41080,
  },
  {
    stopId: 30209,
    dir: "N",
    stopName: "47th (Harlem-bound)",
    parentStopId: 41080,
  },
  {
    stopId: 30237,
    dir: "N",
    stopName: "47th (Howard-bound)",
    parentStopId: 41230,
  },
  {
    stopId: 30238,
    dir: "S",
    stopName: "47th (95th-bound)",
    parentStopId: 41230,
  },
  {
    stopId: 30024,
    dir: "N",
    stopName: "51st (Harlem-bound)",
    parentStopId: 40130,
  },
  {
    stopId: 30025,
    dir: "S",
    stopName: "51st (63rd-bound)",
    parentStopId: 40130,
  },
  {
    stopId: 30113,
    dir: "E",
    stopName: "54th/Cermak (Loop-bound)",
    parentStopId: 40580,
  },
  {
    stopId: 30114,
    dir: "W",
    stopName: "54th/Cermak (Terminal arrival)",
    parentStopId: 40580,
  },
  {
    stopId: 30177,
    dir: "N",
    stopName: "63rd (Howard-bound)",
    parentStopId: 40910,
  },
  {
    stopId: 30178,
    dir: "S",
    stopName: "63rd (95th-bound)",
    parentStopId: 40910,
  },
  {
    stopId: 30191,
    dir: "N",
    stopName: "69th (Howard-bound)",
    parentStopId: 40990,
  },
  {
    stopId: 30192,
    dir: "S",
    stopName: "69th (95th-bound)",
    parentStopId: 40990,
  },
  {
    stopId: 30046,
    dir: "N",
    stopName: "79th (Howard-bound)",
    parentStopId: 40240,
  },
  {
    stopId: 30047,
    dir: "S",
    stopName: "79th (95th-bound)",
    parentStopId: 40240,
  },
  {
    stopId: 30275,
    dir: "N",
    stopName: "87th (Howard-bound)",
    parentStopId: 41430,
  },
  {
    stopId: 30276,
    dir: "S",
    stopName: "87th (95th-bound)",
    parentStopId: 41430,
  },
  {
    stopId: 30089,
    dir: "S",
    stopName: "95th/Dan Ryan (95th-bound)",
    parentStopId: 40450,
  },
  {
    stopId: 30088,
    dir: "N",
    stopName: "95th/Dan Ryan (Howard-bound)",
    parentStopId: 40450,
  },
  {
    stopId: 30132,
    dir: "S",
    stopName: "Adams/Wabash (Inner Loop)",
    parentStopId: 40680,
  },
  {
    stopId: 30131,
    dir: "N",
    stopName: "Adams/Wabash (Outer Loop)",
    parentStopId: 40680,
  },
  {
    stopId: 30240,
    dir: "S",
    stopName: "Addison (Forest Pk-bound)",
    parentStopId: 41240,
  },
  {
    stopId: 30239,
    dir: "N",
    stopName: "Addison (O'Hare-bound)",
    parentStopId: 41240,
  },
  {
    stopId: 30277,
    dir: "N",
    stopName: "Addison (Kimball-bound)",
    parentStopId: 41440,
  },
  {
    stopId: 30278,
    dir: "S",
    stopName: "Addison (Loop-bound)",
    parentStopId: 41440,
  },
  {
    stopId: 30274,
    dir: "S",
    stopName: "Addison (95th-bound)",
    parentStopId: 41420,
  },
  {
    stopId: 30273,
    dir: "N",
    stopName: "Addison (Howard-bound)",
    parentStopId: 41420,
  },
  {
    stopId: 30229,
    dir: "N",
    stopName: "Argyle (Howard-bound)",
    parentStopId: 41200,
  },
  {
    stopId: 30230,
    dir: "S",
    stopName: "Argyle (95th-bound)",
    parentStopId: 41200,
  },
  {
    stopId: 30128,
    dir: "S",
    stopName: "Armitage (Loop-bound)",
    parentStopId: 40660,
  },
  {
    stopId: 30127,
    dir: "N",
    stopName: "Armitage (Kimball-Linden-bound)",
    parentStopId: 40660,
  },
  {
    stopId: 30032,
    dir: "E",
    stopName: "Ashland (Loop-63rd-bound)",
    parentStopId: 40170,
  },
  {
    stopId: 30033,
    dir: "W",
    stopName: "Ashland (Harlem-54th/Cermak-bound)",
    parentStopId: 40170,
  },
  {
    stopId: 30205,
    dir: "N",
    stopName: "Ashland (Loop-bound)",
    parentStopId: 41060,
  },
  {
    stopId: 30206,
    dir: "S",
    stopName: "Ashland (Midway-bound)",
    parentStopId: 41060,
  },
  {
    stopId: 30057,
    dir: "W",
    stopName: "Ashland/63rd (Terminal arrival)",
    parentStopId: 40290,
  },
  {
    stopId: 30056,
    dir: "E",
    stopName: "Ashland/63rd (Harlem-bound)",
    parentStopId: 40290,
  },
  {
    stopId: 30001,
    dir: "E",
    stopName: "Austin (O'Hare-bound)",
    parentStopId: 40010,
  },
  {
    stopId: 30002,
    dir: "W",
    stopName: "Austin (Forest Pk-bound)",
    parentStopId: 40010,
  },
  {
    stopId: 30243,
    dir: "E",
    stopName: "Austin (63rd-bound)",
    parentStopId: 41260,
  },
  {
    stopId: 30244,
    dir: "W",
    stopName: "Austin (Harlem-bound)",
    parentStopId: 41260,
  },
  {
    stopId: 30013,
    dir: "S",
    stopName: "Belmont (O'Hare Branch) (Forest Pk-bound)",
    parentStopId: 40060,
  },
  {
    stopId: 30012,
    dir: "N",
    stopName: "Belmont (O'Hare Branch) (O'Hare-bound)",
    parentStopId: 40060,
  },
  {
    stopId: 30258,
    dir: "S",
    stopName: "Belmont (Loop-bound)",
    parentStopId: 41320,
  },
  {
    stopId: 30256,
    dir: "S",
    stopName: "Belmont (95th-bound)",
    parentStopId: 41320,
  },
  {
    stopId: 30255,
    dir: "N",
    stopName: "Belmont (Howard-bound)",
    parentStopId: 41320,
  },
  {
    stopId: 30257,
    dir: "N",
    stopName: "Belmont (Kimball-Linden-bound)",
    parentStopId: 41320,
  },
  {
    stopId: 30067,
    dir: "S",
    stopName: "Berwyn (95th-bound)",
    parentStopId: 40340,
  },
  {
    stopId: 30066,
    dir: "N",
    stopName: "Berwyn (Howard-bound)",
    parentStopId: 40340,
  },
  {
    stopId: 30267,
    dir: "N",
    stopName: "Bryn Mawr (Howard-bound)",
    parentStopId: 41380,
  },
  {
    stopId: 30268,
    dir: "S",
    stopName: "Bryn Mawr (95th-bound)",
    parentStopId: 41380,
  },
  {
    stopId: 30112,
    dir: "S",
    stopName: "California (Forest Pk-bound)",
    parentStopId: 40570,
  },
  {
    stopId: 30111,
    dir: "N",
    stopName: "California (O'Hare-bound)",
    parentStopId: 40570,
  },
  {
    stopId: 30266,
    dir: "W",
    stopName: "California (Harlem-bound)",
    parentStopId: 41360,
  },
  {
    stopId: 30265,
    dir: "E",
    stopName: "California (63rd-bound)",
    parentStopId: 41360,
  },
  {
    stopId: 30086,
    dir: "E",
    stopName: "California (Loop-bound)",
    parentStopId: 40440,
  },
  {
    stopId: 30087,
    dir: "W",
    stopName: "California (54th/Cermak-bound)",
    parentStopId: 40440,
  },
  {
    stopId: 30055,
    dir: "W",
    stopName: "Central (Harlem-bound)",
    parentStopId: 40280,
  },
  {
    stopId: 30054,
    dir: "E",
    stopName: "Central (63rd-bound)",
    parentStopId: 40280,
  },
  {
    stopId: 30242,
    dir: "S",
    stopName: "Central (Howard-Loop-bound)",
    parentStopId: 41250,
  },
  {
    stopId: 30241,
    dir: "N",
    stopName: "Central (Linden-bound)",
    parentStopId: 41250,
  },
  {
    stopId: 30151,
    dir: "E",
    stopName: "Central Park (Loop-bound)",
    parentStopId: 40780,
  },
  {
    stopId: 30152,
    dir: "W",
    stopName: "Central Park (54th/Cermak-bound)",
    parentStopId: 40780,
  },
  {
    stopId: 30194,
    dir: "S",
    stopName: "Cermak-Chinatown (95th-bound)",
    parentStopId: 41000,
  },
  {
    stopId: 30193,
    dir: "N",
    stopName: "Cermak-Chinatown (Howard-bound)",
    parentStopId: 41000,
  },
  {
    stopId: 30382,
    dir: "S",
    stopName: "Cermak-McCormick Place (63rd-bound)",
    parentStopId: 41690,
  },
  {
    stopId: 30381,
    dir: "N",
    stopName: "Cermak-McCormick Place (Harlem-bound)",
    parentStopId: 41690,
  },
  {
    stopId: 30271,
    dir: "N",
    stopName: "Chicago (O'Hare-bound)",
    parentStopId: 41410,
  },
  {
    stopId: 30272,
    dir: "S",
    stopName: "Chicago (Forest Pk-bound)",
    parentStopId: 41410,
  },
  {
    stopId: 30138,
    dir: "S",
    stopName: "Chicago (Loop-bound)",
    parentStopId: 40710,
  },
  {
    stopId: 30137,
    dir: "N",
    stopName: "Chicago (Kimball-Linden-bound)",
    parentStopId: 40710,
  },
  {
    stopId: 30279,
    dir: "N",
    stopName: "Chicago (Howard-bound)",
    parentStopId: 41450,
  },
  {
    stopId: 30280,
    dir: "S",
    stopName: "Chicago (95th-bound)",
    parentStopId: 41450,
  },
  {
    stopId: 30187,
    dir: "E",
    stopName: "Cicero (O'Hare-bound)",
    parentStopId: 40970,
  },
  {
    stopId: 30188,
    dir: "W",
    stopName: "Cicero (Forest Pk-bound)",
    parentStopId: 40970,
  },
  {
    stopId: 30009,
    dir: "W",
    stopName: "Cicero (Harlem-bound)",
    parentStopId: 40480,
  },
  {
    stopId: 30094,
    dir: "E",
    stopName: "Cicero (63rd-bound)",
    parentStopId: 40480,
  },
  {
    stopId: 30083,
    dir: "W",
    stopName: "Cicero (54th/Cermak-bound)",
    parentStopId: 40420,
  },
  {
    stopId: 30082,
    dir: "E",
    stopName: "Cicero (Loop-bound)",
    parentStopId: 40420,
  },
  {
    stopId: 30122,
    dir: "S",
    stopName: "Clark/Division (95th-bound)",
    parentStopId: 40630,
  },
  {
    stopId: 30121,
    dir: "N",
    stopName: "Clark/Division (Howard-bound)",
    parentStopId: 40630,
  },
  {
    stopId: 30074,
    dir: "E",
    stopName: "Clark/Lake (Inner Loop)",
    parentStopId: 40380,
  },
  {
    stopId: 30075,
    dir: "W",
    stopName: "Clark/Lake (Outer Loop)",
    parentStopId: 40380,
  },
  {
    stopId: 30374,
    dir: "S",
    stopName: "Clark/Lake (Forest Pk-bound)",
    parentStopId: 40380,
  },
  {
    stopId: 30375,
    dir: "N",
    stopName: "Clark/Lake (O'Hare-bound)",
    parentStopId: 40380,
  },
  {
    stopId: 30085,
    dir: "W",
    stopName: "Clinton (Forest Pk-bound)",
    parentStopId: 40430,
  },
  {
    stopId: 30084,
    dir: "E",
    stopName: "Clinton (O'Hare-bound)",
    parentStopId: 40430,
  },
  {
    stopId: 30222,
    dir: "W",
    stopName: "Clinton (Harlem-54th/Cermak-bound)",
    parentStopId: 41160,
  },
  {
    stopId: 30221,
    dir: "E",
    stopName: "Clinton (Loop-63rd-bound)",
    parentStopId: 41160,
  },
  {
    stopId: 30291,
    dir: "E",
    stopName: "Conservatory (63rd-bound)",
    parentStopId: 41670,
  },
  {
    stopId: 30292,
    dir: "W",
    stopName: "Conservatory (Harlem-bound)",
    parentStopId: 41670,
  },
  {
    stopId: 30140,
    dir: "W",
    stopName: "Cottage Grove (Harlem-bound)",
    parentStopId: 40720,
  },
  {
    stopId: 30139,
    dir: "E",
    stopName: "Cottage Grove (Terminal arrival)",
    parentStopId: 40720,
  },
  {
    stopId: 30044,
    dir: "N",
    stopName: "Cumberland (O'Hare-bound)",
    parentStopId: 40230,
  },
  {
    stopId: 30045,
    dir: "S",
    stopName: "Cumberland (Forest Pk-bound)",
    parentStopId: 40230,
  },
  {
    stopId: 30116,
    dir: "S",
    stopName: "Damen/Milwaukee (Forest Pk-bound)",
    parentStopId: 40590,
  },
  {
    stopId: 30115,
    dir: "N",
    stopName: "Damen/Milwaukee (O'Hare-bound)",
    parentStopId: 40590,
  },
  {
    stopId: 30019,
    dir: "S",
    stopName: "Damen (Loop-bound)",
    parentStopId: 40090,
  },
  {
    stopId: 30018,
    dir: "N",
    stopName: "Damen (Kimball-bound)",
    parentStopId: 40090,
  },
  {
    stopId: 30041,
    dir: "W",
    stopName: "Damen (54th/Cermak-bound)",
    parentStopId: 40210,
  },
  {
    stopId: 30040,
    dir: "E",
    stopName: "Damen (Loop-bound)",
    parentStopId: 40210,
  },
  {
    stopId: 30010,
    dir: "N",
    stopName: "Davis (Linden-bound)",
    parentStopId: 40050,
  },
  {
    stopId: 30011,
    dir: "S",
    stopName: "Davis (Howard-Loop-bound)",
    parentStopId: 40050,
  },
  {
    stopId: 30133,
    dir: "N",
    stopName: "Dempster (Linden-bound)",
    parentStopId: 40690,
  },
  {
    stopId: 30134,
    dir: "S",
    stopName: "Dempster (Howard-Loop-bound)",
    parentStopId: 40690,
  },
  {
    stopId: 30026,
    dir: "N",
    stopName: "Dempster-Skokie (Arrival)",
    parentStopId: 40140,
  },
  {
    stopId: 30027,
    dir: "S",
    stopName: "Dempster-Skokie (Howard-bound)",
    parentStopId: 40140,
  },
  {
    stopId: 30103,
    dir: "N",
    stopName: "Diversey (Kimball-Linden-bound)",
    parentStopId: 40530,
  },
  {
    stopId: 30104,
    dir: "S",
    stopName: "Diversey (Loop-bound)",
    parentStopId: 40530,
  },
  {
    stopId: 30062,
    dir: "N",
    stopName: "Division (O'Hare-bound)",
    parentStopId: 40320,
  },
  {
    stopId: 30063,
    dir: "S",
    stopName: "Division (Forest Pk-bound)",
    parentStopId: 40320,
  },
  {
    stopId: 30077,
    dir: "W",
    stopName: "Forest Park (Terminal Arrival)",
    parentStopId: 40390,
  },
  {
    stopId: 30076,
    dir: "E",
    stopName: "Forest Park (O'Hare-bound)",
    parentStopId: 40390,
  },
  {
    stopId: 30101,
    dir: "N",
    stopName: "Foster (Linden-bound)",
    parentStopId: 40520,
  },
  {
    stopId: 30102,
    dir: "S",
    stopName: "Foster (Howard-Loop-bound)",
    parentStopId: 40520,
  },
  {
    stopId: 30168,
    dir: "S",
    stopName: "Francisco (Loop-bound)",
    parentStopId: 40870,
  },
  {
    stopId: 30167,
    dir: "N",
    stopName: "Francisco (Kimball-bound)",
    parentStopId: 40870,
  },
  {
    stopId: 30234,
    dir: "S",
    stopName: "Fullerton (95th-bound)",
    parentStopId: 41220,
  },
  {
    stopId: 30236,
    dir: "S",
    stopName: "Fullerton (Loop-bound)",
    parentStopId: 41220,
  },
  {
    stopId: 30235,
    dir: "N",
    stopName: "Fullerton (Kimball-Linden-bound)",
    parentStopId: 41220,
  },
  {
    stopId: 30233,
    dir: "N",
    stopName: "Fullerton (Howard-bound)",
    parentStopId: 41220,
  },
  {
    stopId: 30100,
    dir: "S",
    stopName: "Garfield (63rd-bound)",
    parentStopId: 40510,
  },
  {
    stopId: 30099,
    dir: "N",
    stopName: "Garfield (Harlem-bound)",
    parentStopId: 40510,
  },
  {
    stopId: 30224,
    dir: "S",
    stopName: "Garfield (95th-bound)",
    parentStopId: 41170,
  },
  {
    stopId: 30223,
    dir: "N",
    stopName: "Garfield (Howard-bound)",
    parentStopId: 41170,
  },
  {
    stopId: 30096,
    dir: "S",
    stopName: "Grand/Milwaukee (Forest Pk-bound)",
    parentStopId: 40490,
  },
  {
    stopId: 30095,
    dir: "N",
    stopName: "Grand/Milwaukee (O'Hare-bound)",
    parentStopId: 40490,
  },
  {
    stopId: 30064,
    dir: "N",
    stopName: "Grand/State (Howard-bound)",
    parentStopId: 40330,
  },
  {
    stopId: 30065,
    dir: "S",
    stopName: "Grand/State (95th-bound)",
    parentStopId: 40330,
  },
  {
    stopId: 30148,
    dir: "S",
    stopName: "Granville (95th-bound)",
    parentStopId: 40760,
  },
  {
    stopId: 30147,
    dir: "N",
    stopName: "Granville (Howard-bound)",
    parentStopId: 40760,
  },
  {
    stopId: 30183,
    dir: "E",
    stopName: "Halsted/63rd (Harlem-bound)",
    parentStopId: 40940,
  },
  {
    stopId: 30184,
    dir: "W",
    stopName: "Halsted/63rd (Ashland-bound)",
    parentStopId: 40940,
  },
  {
    stopId: 30216,
    dir: "S",
    stopName: "Halsted (Midway-bound)",
    parentStopId: 41130,
  },
  {
    stopId: 30215,
    dir: "N",
    stopName: "Halsted (Loop-bound)",
    parentStopId: 41130,
  },
  {
    stopId: 30189,
    dir: "E",
    stopName: "Harlem (Forest Pk Branch) (O'Hare-bound)",
    parentStopId: 40980,
  },
  {
    stopId: 30190,
    dir: "W",
    stopName: "Harlem (Forest Pk Branch) (Terminal arrival)",
    parentStopId: 40980,
  },
  {
    stopId: 30146,
    dir: "S",
    stopName: "Harlem (O'Hare Branch) (Forest Pk-bound)",
    parentStopId: 40750,
  },
  {
    stopId: 30145,
    dir: "N",
    stopName: "Harlem (O'Hare Branch) (O'Hare-bound)",
    parentStopId: 40750,
  },
  {
    stopId: 30003,
    dir: "E",
    stopName: "Harlem (63rd-bound)",
    parentStopId: 40020,
  },
  {
    stopId: 30004,
    dir: "W",
    stopName: "Harlem (Terminal arrival)",
    parentStopId: 40020,
  },
  {
    stopId: 30165,
    dir: "E",
    stopName: "H.W. Library (Outer Loop)",
    parentStopId: 40850,
  },
  {
    stopId: 30166,
    dir: "W",
    stopName: "H.W. Library (Inner Loop)",
    parentStopId: 40850,
  },
  {
    stopId: 30286,
    dir: "S",
    stopName: "Harrison (95th-bound)",
    parentStopId: 41490,
  },
  {
    stopId: 30285,
    dir: "N",
    stopName: "Harrison (Howard-bound)",
    parentStopId: 41490,
  },
  {
    stopId: 30173,
    dir: "N",
    stopName: "Howard (Terminal arrival)",
    parentStopId: 40900,
  },
  {
    stopId: 30176,
    dir: "S",
    stopName: "Howard (Terminal arrival)",
    parentStopId: 40900,
  },
  {
    stopId: 30175,
    dir: "N",
    stopName: "Howard (Linden, Skokie-bound)",
    parentStopId: 40900,
  },
  {
    stopId: 30174,
    dir: "S",
    stopName: "Howard (95th-Bound)",
    parentStopId: 40900,
  },
  {
    stopId: 30157,
    dir: "E",
    stopName: "Illinois Medical District (O'Hare-bound)",
    parentStopId: 40810,
  },
  {
    stopId: 30158,
    dir: "W",
    stopName: "Illinois Medical District (Forest Pk-bound)",
    parentStopId: 40810,
  },
  {
    stopId: 30059,
    dir: "S",
    stopName: "Indiana (63rd-bound)",
    parentStopId: 40300,
  },
  {
    stopId: 30058,
    dir: "N",
    stopName: "Indiana (Harlem-bound)",
    parentStopId: 40300,
  },
  {
    stopId: 30107,
    dir: "N",
    stopName: "Irving Park (O'Hare Branch) (O'Hare-bound)",
    parentStopId: 40550,
  },
  {
    stopId: 30108,
    dir: "S",
    stopName: "Irving Park (O'Hare Branch) (Forest Pk-bound)",
    parentStopId: 40550,
  },
  {
    stopId: 30282,
    dir: "S",
    stopName: "Irving Park (Loop-bound)",
    parentStopId: 41460,
  },
  {
    stopId: 30281,
    dir: "N",
    stopName: "Irving Park (Kimball-bound)",
    parentStopId: 41460,
  },
  {
    stopId: 30014,
    dir: "N",
    stopName: "Jackson/Dearborn (O'Hare-bound)",
    parentStopId: 40070,
  },
  {
    stopId: 30015,
    dir: "S",
    stopName: "Jackson/Dearborn (Forest Pk-bound)",
    parentStopId: 40070,
  },
  {
    stopId: 30110,
    dir: "S",
    stopName: "Jackson/State (95th-bound)",
    parentStopId: 40560,
  },
  {
    stopId: 30109,
    dir: "N",
    stopName: "Jackson/State (Howard-bound)",
    parentStopId: 40560,
  },
  {
    stopId: 30227,
    dir: "N",
    stopName: "Jarvis (Howard-bound)",
    parentStopId: 41190,
  },
  {
    stopId: 30228,
    dir: "S",
    stopName: "Jarvis (95th-bound)",
    parentStopId: 41190,
  },
  {
    stopId: 30247,
    dir: "N",
    stopName: "Jefferson Park (O'Hare-bound)",
    parentStopId: 41280,
  },
  {
    stopId: 30248,
    dir: "S",
    stopName: "Jefferson Park (Forest Pk-bound)",
    parentStopId: 41280,
  },
  {
    stopId: 30226,
    dir: "S",
    stopName: "Kedzie (Loop-bound)",
    parentStopId: 41180,
  },
  {
    stopId: 30225,
    dir: "N",
    stopName: "Kedzie (Kimball-bound)",
    parentStopId: 41180,
  },
  {
    stopId: 30207,
    dir: "E",
    stopName: "Kedzie (63rd-bound)",
    parentStopId: 41070,
  },
  {
    stopId: 30208,
    dir: "W",
    stopName: "Kedzie (Harlem-bound)",
    parentStopId: 41070,
  },
  {
    stopId: 30219,
    dir: "N",
    stopName: "Kedzie (Loop-bound)",
    parentStopId: 41150,
  },
  {
    stopId: 30220,
    dir: "S",
    stopName: "Kedzie (Midway-bound)",
    parentStopId: 41150,
  },
  {
    stopId: 30202,
    dir: "W",
    stopName: "Kedzie (54th/Cermak-bound)",
    parentStopId: 41040,
  },
  {
    stopId: 30201,
    dir: "E",
    stopName: "Kedzie (Loop-bound)",
    parentStopId: 41040,
  },
  {
    stopId: 30049,
    dir: "W",
    stopName: "Kedzie-Homan (Forest Pk-bound)",
    parentStopId: 40250,
  },
  {
    stopId: 30048,
    dir: "E",
    stopName: "Kedzie-Homan (O'Hare-bound)",
    parentStopId: 40250,
  },
  {
    stopId: 30249,
    dir: "N",
    stopName: "Kimball (Terminal arrival)",
    parentStopId: 41290,
  },
  {
    stopId: 30250,
    dir: "S",
    stopName: "Kimball (Loop-bound)",
    parentStopId: 41290,
  },
  {
    stopId: 30217,
    dir: "E",
    stopName: "King Drive (Cottage Grove-bound)",
    parentStopId: 41140,
  },
  {
    stopId: 30218,
    dir: "W",
    stopName: "King Drive (Harlem-bound)",
    parentStopId: 41140,
  },
  {
    stopId: 30117,
    dir: "E",
    stopName: "Kostner (Loop-bound)",
    parentStopId: 40600,
  },
  {
    stopId: 30118,
    dir: "W",
    stopName: "Kostner (54th/Cermak-bound)",
    parentStopId: 40600,
  },
  {
    stopId: 30290,
    dir: "S",
    stopName: "Lake (95th-bound)",
    parentStopId: 41660,
  },
  {
    stopId: 30289,
    dir: "N",
    stopName: "Lake (Howard-bound)",
    parentStopId: 41660,
  },
  {
    stopId: 30135,
    dir: "E",
    stopName: "Laramie (63rd-bound)",
    parentStopId: 40700,
  },
  {
    stopId: 30136,
    dir: "W",
    stopName: "Laramie (Harlem-bound)",
    parentStopId: 40700,
  },
  {
    stopId: 30262,
    dir: "W",
    stopName: "LaSalle (Forest Pk-bound)",
    parentStopId: 41340,
  },
  {
    stopId: 30261,
    dir: "E",
    stopName: "LaSalle (O'Hare-bound)",
    parentStopId: 41340,
  },
  {
    stopId: 30030,
    dir: "E",
    stopName: "LaSalle/Van Buren (Outer Loop)",
    parentStopId: 40160,
  },
  {
    stopId: 30031,
    dir: "W",
    stopName: "LaSalle/Van Buren (Inner Loop)",
    parentStopId: 40160,
  },
  {
    stopId: 30149,
    dir: "N",
    stopName: "Lawrence (Howard-bound)",
    parentStopId: 40770,
  },
  {
    stopId: 30150,
    dir: "S",
    stopName: "Lawrence (95th-bound)",
    parentStopId: 40770,
  },
  {
    stopId: 30203,
    dir: "N",
    stopName: "Linden (Linden-bound)",
    parentStopId: 41050,
  },
  {
    stopId: 30204,
    dir: "S",
    stopName: "Linden (Howard-Loop-bound)",
    parentStopId: 41050,
  },
  {
    stopId: 30197,
    dir: "N",
    stopName: "Logan Square (O'Hare-bound)",
    parentStopId: 41020,
  },
  {
    stopId: 30198,
    dir: "S",
    stopName: "Logan Square (Forest Pk-bound)",
    parentStopId: 41020,
  },
  {
    stopId: 30251,
    dir: "N",
    stopName: "Loyola (Howard-bound)",
    parentStopId: 41300,
  },
  {
    stopId: 30252,
    dir: "S",
    stopName: "Loyola (95th-bound)",
    parentStopId: 41300,
  },
  {
    stopId: 30052,
    dir: "N",
    stopName: "Main (Linden-bound)",
    parentStopId: 40270,
  },
  {
    stopId: 30053,
    dir: "S",
    stopName: "Main (Howard-Loop-bound)",
    parentStopId: 40270,
  },
  {
    stopId: 30091,
    dir: "S",
    stopName: "Merchandise Mart (Loop-bound)",
    parentStopId: 40460,
  },
  {
    stopId: 30090,
    dir: "N",
    stopName: "Merchandise Mart (Kimball-Linden-bound)",
    parentStopId: 40460,
  },
  {
    stopId: 30182,
    dir: "S",
    stopName: "Midway (Arrival)",
    parentStopId: 40930,
  },
  {
    stopId: 30181,
    dir: "N",
    stopName: "Midway (Loop-bound)",
    parentStopId: 40930,
  },
  {
    stopId: 30153,
    dir: "N",
    stopName: "Monroe (O'Hare-bound)",
    parentStopId: 40790,
  },
  {
    stopId: 30154,
    dir: "S",
    stopName: "Monroe (Forest Pk-bound)",
    parentStopId: 40790,
  },
  {
    stopId: 30211,
    dir: "N",
    stopName: "Monroe (Howard-bound)",
    parentStopId: 41090,
  },
  {
    stopId: 30212,
    dir: "S",
    stopName: "Monroe (95th-bound)",
    parentStopId: 41090,
  },
  {
    stopId: 30260,
    dir: "S",
    stopName: "Montrose (Forest Pk-bound)",
    parentStopId: 41330,
  },
  {
    stopId: 30259,
    dir: "N",
    stopName: "Montrose (O'Hare-bound)",
    parentStopId: 41330,
  },
  {
    stopId: 30287,
    dir: "N",
    stopName: "Montrose (Kimball-bound)",
    parentStopId: 41500,
  },
  {
    stopId: 30288,
    dir: "S",
    stopName: "Montrose (Loop-bound)",
    parentStopId: 41500,
  },
  {
    stopId: 30296,
    dir: "W",
    stopName: "Morgan (Harlem-54th/Cermak-bound)",
    parentStopId: 41510,
  },
  {
    stopId: 30295,
    dir: "E",
    stopName: "Morgan (Loop-63rd-bound)",
    parentStopId: 41510,
  },
  {
    stopId: 30020,
    dir: "N",
    stopName: "Morse (Howard-bound)",
    parentStopId: 40100,
  },
  {
    stopId: 30021,
    dir: "S",
    stopName: "Morse (95th-bound)",
    parentStopId: 40100,
  },
  {
    stopId: 30125,
    dir: "N",
    stopName: "North/Clybourn (Howard-bound)",
    parentStopId: 40650,
  },
  {
    stopId: 30126,
    dir: "S",
    stopName: "North/Clybourn (95th-bound)",
    parentStopId: 40650,
  },
  {
    stopId: 30079,
    dir: "S",
    stopName: "Noyes (Howard-Loop-bound)",
    parentStopId: 40400,
  },
  {
    stopId: 30078,
    dir: "N",
    stopName: "Noyes (Linden-bound)",
    parentStopId: 40400,
  },
  {
    stopId: 30035,
    dir: "W",
    stopName: "Oak Park (Forest Pk-bound)",
    parentStopId: 40180,
  },
  {
    stopId: 30034,
    dir: "E",
    stopName: "Oak Park (O'Hare-bound)",
    parentStopId: 40180,
  },
  {
    stopId: 30263,
    dir: "E",
    stopName: "Oak Park (63rd-bound)",
    parentStopId: 41350,
  },
  {
    stopId: 30264,
    dir: "W",
    stopName: "Oak Park (Harlem-bound)",
    parentStopId: 41350,
  },
  {
    stopId: 30298,
    dir: "S",
    stopName: "Oakton-Skokie (Howard-bound)",
    parentStopId: 41680,
  },
  {
    stopId: 30297,
    dir: "N",
    stopName: "Oakton-Skokie (Dempster-Skokie-bound)",
    parentStopId: 41680,
  },
  {
    stopId: 30172,
    dir: "S",
    stopName: "O'Hare (Forest Pk-bound)",
    parentStopId: 40890,
  },
  {
    stopId: 30171,
    dir: "N",
    stopName: "O'Hare (Terminal Arrival)",
    parentStopId: 40890,
  },
  {
    stopId: 30254,
    dir: "S",
    stopName: "Paulina (Loop-bound)",
    parentStopId: 41310,
  },
  {
    stopId: 30253,
    dir: "N",
    stopName: "Paulina (Kimball-bound)",
    parentStopId: 41310,
  },
  {
    stopId: 30200,
    dir: "W",
    stopName: "Polk (54th/Cermak-bound)",
    parentStopId: 41030,
  },
  {
    stopId: 30199,
    dir: "E",
    stopName: "Polk (Loop-bound)",
    parentStopId: 41030,
  },
  {
    stopId: 30180,
    dir: "W",
    stopName: "Pulaski (Forest Pk-bound)",
    parentStopId: 40920,
  },
  {
    stopId: 30179,
    dir: "E",
    stopName: "Pulaski (O'Hare-bound)",
    parentStopId: 40920,
  },
  {
    stopId: 30005,
    dir: "E",
    stopName: "Pulaski (63rd-bound)",
    parentStopId: 40030,
  },
  {
    stopId: 30006,
    dir: "W",
    stopName: "Pulaski (Harlem-bound)",
    parentStopId: 40030,
  },
  {
    stopId: 30185,
    dir: "N",
    stopName: "Pulaski (Loop-bound)",
    parentStopId: 40960,
  },
  {
    stopId: 30186,
    dir: "S",
    stopName: "Pulaski (Midway-bound)",
    parentStopId: 40960,
  },
  {
    stopId: 30028,
    dir: "E",
    stopName: "Pulaski (Loop-bound)",
    parentStopId: 40150,
  },
  {
    stopId: 30029,
    dir: "W",
    stopName: "Pulaski (54th/Cermak-bound)",
    parentStopId: 40150,
  },
  {
    stopId: 30007,
    dir: "N",
    stopName: "Quincy/Wells (Inner Loop)",
    parentStopId: 40040,
  },
  {
    stopId: 30008,
    dir: "S",
    stopName: "Quincy/Wells (Outer Loop)",
    parentStopId: 40040,
  },
  {
    stopId: 30093,
    dir: "W",
    stopName: "Racine (Forest Pk-bound)",
    parentStopId: 40470,
  },
  {
    stopId: 30092,
    dir: "E",
    stopName: "Racine (O'Hare-bound)",
    parentStopId: 40470,
  },
  {
    stopId: 30120,
    dir: "W",
    stopName: "Ridgeland (Harlem-bound)",
    parentStopId: 40610,
  },
  {
    stopId: 30119,
    dir: "E",
    stopName: "Ridgeland (63rd-bound)",
    parentStopId: 40610,
  },
  {
    stopId: 30196,
    dir: "S",
    stopName: "Rockwell (Loop-bound)",
    parentStopId: 41010,
  },
  {
    stopId: 30195,
    dir: "N",
    stopName: "Rockwell (Kimball-bound)",
    parentStopId: 41010,
  },
  {
    stopId: 30081,
    dir: "S",
    stopName: "Roosevelt (Midway-63rd-bound)",
    parentStopId: 41400,
  },
  {
    stopId: 30080,
    dir: "N",
    stopName: "Roosevelt (Loop-Harlem-bound)",
    parentStopId: 41400,
  },
  {
    stopId: 30269,
    dir: "N",
    stopName: "Roosevelt (Howard-bound)",
    parentStopId: 41400,
  },
  {
    stopId: 30270,
    dir: "S",
    stopName: "Roosevelt (95th-bound)",
    parentStopId: 41400,
  },
  {
    stopId: 30159,
    dir: "N",
    stopName: "Rosemont (O'Hare-bound)",
    parentStopId: 40820,
  },
  {
    stopId: 30160,
    dir: "S",
    stopName: "Rosemont (Forest Pk-bound)",
    parentStopId: 40820,
  },
  {
    stopId: 30155,
    dir: "N",
    stopName: "Sedgwick (Kimball-Linden-bound)",
    parentStopId: 40800,
  },
  {
    stopId: 30156,
    dir: "S",
    stopName: "Sedgwick (Loop-bound)",
    parentStopId: 40800,
  },
  {
    stopId: 30017,
    dir: "S",
    stopName: "Sheridan (95th-bound)",
    parentStopId: 40080,
  },
  {
    stopId: 30016,
    dir: "N",
    stopName: "Sheridan (Howard-bound)",
    parentStopId: 40080,
  },
  {
    stopId: 30293,
    dir: "N",
    stopName: "Sheridan (Howard-Linden-bound)",
    parentStopId: 40080,
  },
  {
    stopId: 30294,
    dir: "S",
    stopName: "Sheridan (Loop-bound)",
    parentStopId: 40080,
  },
  {
    stopId: 30163,
    dir: "N",
    stopName: "South Blvd (Linden-bound)",
    parentStopId: 40840,
  },
  {
    stopId: 30164,
    dir: "S",
    stopName: "South Blvd (Howard-Loop-bound)",
    parentStopId: 40840,
  },
  {
    stopId: 30070,
    dir: "N",
    stopName: "Southport (Kimball-bound)",
    parentStopId: 40360,
  },
  {
    stopId: 30071,
    dir: "S",
    stopName: "Southport (Loop-bound)",
    parentStopId: 40360,
  },
  {
    stopId: 30036,
    dir: "N",
    stopName: "Sox-35th (Howard-bound)",
    parentStopId: 40190,
  },
  {
    stopId: 30037,
    dir: "S",
    stopName: "Sox-35th (95th-bound)",
    parentStopId: 40190,
  },
  {
    stopId: 30051,
    dir: "W",
    stopName: "State/Lake (Outer Loop)",
    parentStopId: 40260,
  },
  {
    stopId: 30050,
    dir: "E",
    stopName: "State/Lake (Inner Loop)",
    parentStopId: 40260,
  },
  {
    stopId: 30170,
    dir: "S",
    stopName: "Thorndale (95th-bound)",
    parentStopId: 40880,
  },
  {
    stopId: 30169,
    dir: "N",
    stopName: "Thorndale (Howard-bound)",
    parentStopId: 40880,
  },
  {
    stopId: 30069,
    dir: "W",
    stopName: "UIC-Halsted (Forest Pk-bound)",
    parentStopId: 40350,
  },
  {
    stopId: 30068,
    dir: "E",
    stopName: "UIC-Halsted (O'Hare-bound)",
    parentStopId: 40350,
  },
  {
    stopId: 30073,
    dir: "S",
    stopName: "Washington (Forest Pk-bound)",
    parentStopId: 40370,
  },
  {
    stopId: 30072,
    dir: "N",
    stopName: "Washington (O'Hare-bound)",
    parentStopId: 40370,
  },
  {
    stopId: 30383,
    dir: "N",
    stopName: "Washington/Wabash (Outer Loop)",
    parentStopId: 41700,
  },
  {
    stopId: 30384,
    dir: "S",
    stopName: "Washington/Wabash (Inner Loop)",
    parentStopId: 41700,
  },
  {
    stopId: 30141,
    dir: "N",
    stopName: "Washington/Wells (Inner Loop)",
    parentStopId: 40730,
  },
  {
    stopId: 30142,
    dir: "S",
    stopName: "Washington/Wells (Outer Loop)",
    parentStopId: 40730,
  },
  {
    stopId: 30231,
    dir: "N",
    stopName: "Wellington (Kimball-Linden-bound)",
    parentStopId: 41210,
  },
  {
    stopId: 30232,
    dir: "S",
    stopName: "Wellington (Loop-bound)",
    parentStopId: 41210,
  },
  {
    stopId: 30042,
    dir: "E",
    stopName: "Western (Forest Pk Branch) (O'Hare-bound)",
    parentStopId: 40220,
  },
  {
    stopId: 30043,
    dir: "W",
    stopName: "Western (Forest Pk Branch) (Forest Pk-bound)",
    parentStopId: 40220,
  },
  {
    stopId: 30129,
    dir: "N",
    stopName: "Western (O'Hare Branch) (O'Hare-bound)",
    parentStopId: 40670,
  },
  {
    stopId: 30130,
    dir: "S",
    stopName: "Western (O'Hare Branch) (Forest Pk-bound)",
    parentStopId: 40670,
  },
  {
    stopId: 30284,
    dir: "S",
    stopName: "Western (Loop-bound)",
    parentStopId: 41480,
  },
  {
    stopId: 30283,
    dir: "N",
    stopName: "Western (Kimball-bound)",
    parentStopId: 41480,
  },
  {
    stopId: 30061,
    dir: "S",
    stopName: "Western (Midway-bound)",
    parentStopId: 40310,
  },
  {
    stopId: 30060,
    dir: "N",
    stopName: "Western (Loop-bound)",
    parentStopId: 40310,
  },
  {
    stopId: 30143,
    dir: "E",
    stopName: "Western (Loop-bound)",
    parentStopId: 40740,
  },
  {
    stopId: 30144,
    dir: "W",
    stopName: "Western (54th/Cermak-bound)",
    parentStopId: 40740,
  },
  {
    stopId: 30106,
    dir: "S",
    stopName: "Wilson (95th-bound)",
    parentStopId: 40540,
  },
  {
    stopId: 30105,
    dir: "N",
    stopName: "Wilson (Howard-bound)",
    parentStopId: 40540,
  },
  {
    stopId: 30385,
    dir: "S",
    stopName: "Wilson (Loop-bound)",
    parentStopId: 40540,
  },
  {
    stopId: 30386,
    dir: "N",
    stopName: "Wilson (Linden-bound)",
    parentStopId: 40540,
  },
];